### ISSUE TITLE
fs is undefined 

### ISSUE THREAD

**Issue by abeaclark** [RizeFinance/rize-js#133]
Very possible this is user error and not a bug, if so, would love to know if you see what I am doing wrong.

**Describe the bug**
When instantiating the `Rize` class, I get `ReferenceError: fs is not defined`

**To Reproduce**
See repro by running `yarn start`: https://github.com/abeaclark/rize-message-proxy

**Expected behavior**
Able to instantiate client

**Additional context**
This is my first attempt at using the sdk, so it's very possible I'm doing something wrong
Also, the docs show:
```
const Rize = require('@rizefinance/rize-js');
```
but it seems you've published to npm as `rize-js`?

**Comment by ksalmon** [comment]
@abeaclark Thanks for reaching out. Diving into this and will get a response back before EOD!

**Comment by ksalmon** [comment]
@abeaclark 

Our package is hosted on the Github Registry. Please don't use this [package](https://www.npmjs.com/package/rize-js) (it's not ours)

Your package.json file should look like this
`{
  "name": "rize-message-proxy",
  "version": "1.0.0",
  "description": "Pass through of Rize events to google pub/sub",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@rizefinance/rize-js": "^1.3.0",
    "dotenv": "^10.0.0"
  }
}
`

Also on index.js line 2 should read like this
`const Rize = require('@rizefinance/rize-js');`
 
I'll close this out once you have confirmed you have bypassed this specific issue. 

PS: I attempted to push up a PR to your repo but was denied (which makes sense) 😜

**Comment by abeaclark** [comment]
Got it! Thank you for your help on this one.

I was a bit confused on how to set this up when using Yarn. But it seems like the npm command you provide in the readme works!

Big thanks. I'm sure I'll come back with more questions.
